# Install
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yaml

  tasks:
    - name: Install prerequisites
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes 

    - name: Install LAMP Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'python-mysqldb', 'mysql-server', 'mysql-client', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' , 'python-apt', 'python3-apt', 'python3-pymysql', 'python-pymysql', 'python3-pymysql', 'python-apt', 'python3-apt']
      tags: [ system ]

    - name: Install PHP Extensions
      apt: name={{ item }} update_cache=yes state=latest
      loop: "{{ php_modules }}"
      tags: [ system ]

  # Apache Configuration
    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: '0755'
      tags: [ apache ]

    - name: Set up Apache VirtualHost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache
      tags: [ apache ]

    - name: Enable rewrite module
      shell: /usr/sbin/a2enmod rewrite
      notify: Reload Apache
      tags: [ apache ]

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache
      tags: [ apache ]

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      notify: Restart Apache
      tags: [ apache ]

  # MySQL Configuration

    - name: Set the root password
      mysql_user:
        name: "{{ mysql_root_password }}"
        encoding: utf8
        login_unix_socket: /var/run/mysqld/mysqld.sock
      tags: 1my
#
    - name: Remove all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: 2my

    - name: Remove the MySQL test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: 3my
    
    - name: Creates database for WordPress
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: password
        login_password: "{{ mysql_root_password }}"
      tags: 4my

  #  - name: Create MySQL user for WordPress
  #    mysql_user:
  #      name: "{{ mysql_user }}"
  #      password: "{{ mysql_password }}"
  #      priv: "{{ mysql_db }}.*:ALL"
  #      state: present
  #      login_user: password
  #      login_password: "{{ mysql_root_password }}"
  #    tags: 5my

  # UFW Configuration
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        to_port: '80'
        proto: tcp
      tags: 1s

  # WordPress Configuration
    - name: Download and unpack WordPress 5.2.10
      unarchive:
        src: https://wordpress.org/wordpress-5.2.10.tar.gz
        dest: "/var/www/{{ http_host }}"
        remote_src: yes
        creates: "/var/www/{{ http_host }}/wordpress"
      tags: 2s

    - name: Set ownership
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
      tags: 3s

    - name: Set permissions for directories
      shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type d -exec chmod 750 {} \\;"
      tags: 4s

    - name: Set permissions for files
      shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type f -exec chmod 640 {} \\;"
      tags: 5s

    - name: Set up wp-config
      template:
        src: "files/wp-config.php.j2"
        dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"
      tags: 6s
    
   
  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
