- name: apt | update repository cache
  apt: 
    update_cache: yes
- name: Install packages
  apt:
    name: "{{ apt_packages }}"
    state: latest
- name: MySQL. Install and setup
  template: 
    src: my.cnf.j2 
    dest: ~/.my.cnf 
    owner: root 
    mode: 0600
  notify: mysql restart 
- meta: flush_handlers
#- mysql_db:
#    name: "{{ app_db_name }}"
#    encoding: utf8
#    login_unix_socket: /var/run/mysqld/mysqld.sock
- mysql_user:
    name: "{{ app_db_user }}"
    password: "{{ app_db_pass }}"
    priv: "{{ app_db_name }}.*:ALL"

- name: Processwire. Clone repository
  git: 
   repo: "{{ app_repo }}" 
   dest: "{{ app_home }}" 
   version: '{{ app_version }}' 
   accept_hostkey: yes
   force: yes

- name: Processwire. Change owner
  file:
    path: "{{ app_home }}"
    owner: www-data
    group: www-data
    recurse: yes
- name: Processwire. Change permissions
  file:
    path: "{{ app_home }}"
    mode: '777'
    recurse: yes

- name: Configuration files for virtualhost
  template:
    src: processwire.site.conf.j2
    dest: "/etc/apache2/sites-enabled/processwire.conf"
  notify:
    - restart apache2
  tags:
    - apache::setup
- name: Enable rewrite module for Apache
  apache2_module:
    state: present
    name: rewrite
  notify:
    - restart apache2  
- name: "Add {{ app_fqdn }} to host file"
  shell: echo "127.0.0.1       {{ app_fqdn }}" >> /etc/hosts
  tags: 
    - test
#- uri:
#    url: "http://{{ app_fqdn }}"
#    return_content: yes
#  register: this
# failed_when: "'asdfdf' not in this.content"
#  tags: 
#    - test
- lineinfile:
    path: /etc/hosts
    state: absent
    regexp: '^127.0.0.1       {{ app_fqdn }}'
  tags: 
    - test 
    
    
    
 #     apt: name={{ item }} update_cache=yes state=latest
#  loop: ['php7.2-cgi', 'libapache2-mod-php7.2',  'php7.2-xmlrpc', 'php7.2-gd', 'php7.2-mbstring', 'php7.2-common', 'php7.2-xmlrpc', 'php7.2-soap', 'php7.2-xml', 'php7.2-intl', 'php7.2-cli', 'php7.2-ldap', 'php7.2-zip', 'php7.2-readline', 'php7.2-imap', 'php7.2-tidy', 'php7.2-recode', 'php7.2-intl', 'libmysqlclient-dev', 'python-pymysql','python-mysqldb', 'imagemagick', 'libssl-dev', 'libmagickwand-dev', 'libapache2-mod-passenger', 'build-essential', 'php7.2-json', 'php7.2-curl', 'php7.2-mysql', 'php7.2', 'wget', 'unzip ', 'default-mysql-server', 'mariadb-client', 'mariadb-server', 'apache2']
